apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-frontend
  template:
    metadata:
      labels:
        app: agent-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image.frontend }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.frontendPort }}

